dependencies:
  - changed-files:
      - package.json
      - yarn.lock

frontend:
  - changed-files:
      - "src/**/*.{ts,tsx}"
      - "public/**/*"
      - "style/**/*.{css,scss}"
      - "lib/**/*.{ts,tsx}"

config:
  - changed-files:
      - "*.config.js"
      - "*.config.mjs"
      - "tsconfig.json"
      - ".prettierrc"
      - ".yarnrc.yml"
      - ".gitignore"

github-actions:
  - changed-files:
      - ".github/**/*"

docs:
  - changed-files:
      - "**/*.md"
      - "README.md"
